language: ruby
rvm:
  - 2.6.3

addons:
  chrome: stable

services:
  - postgresql

before_script:
  - gem install brakeman
  - gem install bundler-audit
  - SECRET_KEY_BASE=IGNORE_ME_I_AM_A_BAD_KEY_BASE bundle exec rake assets:precompile
  - bundle exec rake db:test:prepare

script:
  - bundle-audit --update
  - brakeman --no-pager --github-repo maxfierke/resumis
  - bundle exec rake spec
